version: "3"
services:
  traefik:
    restart: always
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http,https
      - traefik.http.routers.traefik.rule=Host(`traefik.this.test`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal

networks:
  default:
    name: docker
    external: true
